# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "85debeba7a29bfb199d1b9064024b91c"
name = "wakubo-semantic-search"
application_url = "https://ungenerical-dimple-unvacuously.ngrok-free.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

    [[webhooks.subscriptions]]
    topics = ["products/create", "products/update", "products/delete"]
    uri = "https://ungenerical-dimple-unvacuously.ngrok-free.dev/webhooks/shopify"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://ungenerical-dimple-unvacuously.ngrok-free.dev/auth/callback" ]

[[extensions]]
name = "semantic-search-widget"
handle = "semantic-search-widget"
type = "theme"
